#[macro_use]
extern crate diesel;

/// Logic to download and prepare the [Movielens Dataset](https://grouplens.org/datasets/movielens/).
pub mod dataset;
/// Domain models of the application.
pub mod models;
/// Database schema module auto-generated by [Diesel](https://diesel.rs).
pub mod schema;
